// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsjajvcdzojrohgadznh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzamFqdmNkem9qcm9oZ2Fkem5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODIzNDcsImV4cCI6MjA3MDA1ODM0N30.LaC_PcRkYUyJMjpsLPyivbpNeOb1b_bA7c7pzn8FTAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});